# Generated by Django 4.0.5 on 2022-06-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PersonaId', models.IntegerField(primary_key=True, serialize=False, verbose_name='PersonaId')),
                ('Rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Paterno', models.CharField(max_length=20, verbose_name='Paterno')),
                ('Materno', models.CharField(max_length=20, verbose_name='Materno')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ProductoId', models.IntegerField(primary_key=True, serialize=False, verbose_name='ProductoId')),
                ('Descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('Valor', models.IntegerField(verbose_name='Valor')),
                ('Stock', models.IntegerField(verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('DetalleCarritoId', models.IntegerField(primary_key=True, serialize=False, verbose_name='DetalleCarritoId')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('ProductoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('CarritoId', models.IntegerField(primary_key=True, serialize=False, verbose_name='ProductoId')),
                ('Total', models.IntegerField(verbose_name='Total')),
                ('PersonaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
